presentation_library_app:
    resource: "@PresentationLibraryAppBundle/Controller/"
    type:     annotation
    prefix:   /library/

presentation_library_rest:
    resource: "@PresentationLibraryRestBundle/Controller/"
    type:     annotation
    prefix:   /library/rest/



